[tool.poetry]
name = "apod"
version = "0.1.0"
description = ""
authors = ["Richard Sarkis <rich@sark.is>"]

[tool.poetry.dependencies]
python = "^3.8"
pyobjc = "^9.0.1"
Pillow = "^9.4.0"
requests = "^2.28.2"
structlog = "^22.3.0"
fake-useragent = "^1.1.1"
python-dotenv = "^0.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
